### ISSUE TITLE
Incorrect zoom on page load

### ISSUE THREAD

**Issue by PHLAK** [pehaa/beerslider#10]
This is weird, on page load the left image is improperly zoomed.

![Screen Shot 2020-01-06 at 22 52 39](https://user-images.githubusercontent.com/53531/71871758-7d821380-30d7-11ea-91fa-43b31771ea9d.png)

However, when the page is resized at all it immediately fixes itself (no refresh needed).

![Screen Shot 2020-01-06 at 22 53 00](https://user-images.githubusercontent.com/53531/71871824-aefadf00-30d7-11ea-81a3-531dc723a4cb.png)

I installed Beer Slider via npm and am loading it in my `app.js` file like so

```javascript
let BeerSlider = require('beerslider');

new BeerSlider(document.getElementById('beer-slider'));
```

and my markup

```html
<div id="beer-slider" class="beer-slider rounded-lg shadow-lg mb-6" data-beer-label="Dark">
    <img src="images/screenshot-dark.png" alt="Directory Lister - Dark Theme">

    <div class="beer-reveal" data-beer-label="Light">
        <img src="images/screenshot-light.png" alt="Directory Lister - Light Theme">
    </div>
</div>
```

**Comment by PHLAK** [comment]
Interestingly enough today I changed it to pull the same image from a remote location and it worked correctly every time. Is it possible that the low delay in fetching the (local) image is causing something to happen or not happen before the script is ready?

**Comment by Icywarrior13** [comment]
Hi, what did you do the fix this?  I got the same probleem but i dulon't know how to fix this?

Could you please share? :)

**Comment by PHLAK** [comment]
Here's the code as currently implemented on https://www.directorylister.com:

```javascript
let BeerSlider = require('beerslider');

window.addEventListener('load', function() {
    new BeerSlider(document.getElementById('beer-slider'));
});
```

```html
<div id="beer-slider" class="beer-slider" data-beer-label="Dark">
     <img src="images/screenshot-dark.png">

     <div class="beer-reveal" data-beer-label="Light">
         <img src="images/screenshot-light.png">
     </div>
</div>
```

You can view the complete code here: https://github.com/DirectoryLister/directorylister.com

**Comment by Icywarrior13** [comment]
Thanks for sharing.

I tried the same thing as i can see here. 
When pick local images there is no problem at all. Everything loads fine. 

But for Example, i tried this with stenciljs, {{#each}} product.images {{/each}}. Same problem, left image is very small, right image loads correctly. 

No fix found for it yet, i might get rid of beersliderjs. But it indeed looks like there is a bug when it gets from a api call. :(
